# Форматы данных, используемые в ГИС {#formats}

Основные типы данных, используемые в геоинформационных системах - растровые и векторные данные.

Растровые данные - это матрица или сетка, в каждой ячейке (пикселе) которой содержится числовое значение. В качестве растровых данных могут быть использованы цифровые изображения или значения непрерывных величин (например, рельеф).

В векторных данных местоположение объектов задается с помощью координат и математических формул. В геоинформационных системах используются специализированные форматы векторных данных, позволяющие хранить как информацию о местоположении объектов, так и их атрибутивные (непространственные) характеристики.

Основным форматом векторных данных в ГИС является shapefile[^data-formats-1]. Этот проприетарный формат данных от компании ESRI, который был разработан ими в 90-х годах прошлого века. При использовании этого формата данные хранятся в нескольких файлах с разными расширениями, обязательными из которых являются:

[^data-formats-1]: ESRI Shapefile Technical Description --- Электрон. дан. --- <https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf>

\- .shp - геометрия объектов;

\- .shx - файл индексов необходим для ускорения расчетов и связи геометрии и атрибутов;

\- .dbf - таблица атрибутов:

\- .prj - сведения о проекции и системе координат.

Без перечисленных выше файлов данные не будут корректно открываться и обрабатываться в ГИС.

Основная проблема при работе с описанным форматом в том, что это мультифайловый формат, что необходимо помнить при сохранении и переносе данных.

Постепенно на замену shapefile приходят другие форматы данных, например, GeoJSON - формат представления различных структур географических данных.

Объект GeoJSON может быть представлен геометрией (geometry), объектом (feature) или коллекцией объектов (feature collection). GeoJSON поддерживает следующие геометрические типы: Point (точка), LineString (ломаная), Polygon (полигон), MultiPoint (мультиточка), MultiLineString (мультиломаная), MultiPolygon (мультиполигон) и GeometryCollection (коллекция геометрий). Объект (feature) в GeoJSON состоит из геометрии и дополнительных свойств, коллекция объектов (feature collection) -- из набора объектов (feature).

В GeoJSON объект состоит из набора пар ключ/значение, также называемых свойствами. Имя каждого свойства -- строка. Значение свойства может представлять собой строку, число, объект, массив или один из литералов: «true», «false» и «null». Массив состоит из элементов, где каждый элемент может принимать одно из значений, описанных выше.

Коллекция элементарных объектов GeoJSON:

***`{ "type": "FeatureCollection",`***

***`"features": [`***

***`{ "type": "Feature",`***

***`"geometry": {"type": "Point", "coordinates": [102.0, 0.5]},`***

***`"properties": {"prop0": "value0"}`***

***`},`***

***`{ "type": "Feature",`***

***`"geometry": {`***

***`"type": "LineString",`***

***`"coordinates": [`***

***`[102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]`***

***`]`***

***`},`***

***`"properties": {`***

***`"prop0": "value0",`***

***`"prop1": 0.0`***

***`}`***

***`},`***

***`{ "type": "Feature",`***

***`"geometry": {`***

***`"type": "Polygon",`***

***`"coordinates": [`***

***`[ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],`***

***`[100.0, 1.0], [100.0, 0.0] ]`***

***`]`***

***`},`***

***`"properties": {`***

***`"prop0": "value0",`***

***`"prop1": {"this": "that"}`***

***`}`***

***`}`***

***`]`***

***`}`***

 

Также все более широкое распространение получает формат GeoPackage, который фактически является файлом SQL-базы данных с расширением .gpkg[^data-formats-2].

[^data-formats-2]: Getting Started With GeoPackage --- Электрон. дан. --- <http://www.geopackage.org/guidance/getting-started.html>
