# Примеры заданий для зачета {#exam}

Это пока только примеры заданий, конкретные задания будут чуть позже.

Все задания на зачете делать будет не нужно, только какое-то одно из.

## Задание 1

Построить зоны доступности вокруг объектов, найти и показать на карте, какие здания попадают в эти буферные зоны.

Исходные данные по вариантам приведены ниже.

### Вариант 1

Кафе <https://disk.yandex.ru/d/YmfFkXudwTeF7Q>

Многоквартирные дома <https://disk.yandex.ru/d/9f28RhhB2pz4jw>

Размер зоны доступности 500 м.

### Вариант 2

Пешеходные переходы <https://disk.yandex.ru/d/iHYai2551BHHKw>

Жилые дома <https://disk.yandex.ru/d/a6NCXPTUbh_5Zg>

Размер зоны доступности 100 м.

### Вариант 3

Рестораны <https://disk.yandex.ru/d/pMYjvUyemm2fpg>

Многоквартирные дома <https://disk.yandex.ru/d/S-YQPYSFcC3RgQ>

Размер зоны доступности 1000 м.

## Задание 2

Построить картограмму по плотности населения и оформить ее для печати.

Исходный файл для построения картограмм <https://drive.google.com/file/d/1smnWbvkk1qE4rv5p8QWo108MGqcylMJH/view?usp=sharing>

## Задание 3

Рассчитать площади объектов, добавить цветовую раскраску объектов в зависимости от площади.

Площади должны быть рассчитаны в метрах квадратных.

### Вариант 1

Многоквартирные дома <https://disk.yandex.ru/d/9f28RhhB2pz4jw>

### Вариант 2

Жилые дома <https://disk.yandex.ru/d/a6NCXPTUbh_5Zg>

### Вариант 3

Многоквартирные дома <https://disk.yandex.ru/d/S-YQPYSFcC3RgQ>

## Задание 4

Построить буферные зоны вокруг объектов и найти области в этих зонах, которые не попадают на здания.

### Вариант 1

Кафе <https://disk.yandex.ru/d/YmfFkXudwTeF7Q>

Многоквартирные дома <https://disk.yandex.ru/d/9f28RhhB2pz4jw>

Размер зоны доступности 500 м.

### Вариант 2

Пешеходные переходы <https://disk.yandex.ru/d/iHYai2551BHHKw>

Жилые дома <https://disk.yandex.ru/d/a6NCXPTUbh_5Zg>

Размер зоны доступности 100 м.

### Вариант 3

Рестораны <https://disk.yandex.ru/d/pMYjvUyemm2fpg>

Многоквартирные дома <https://disk.yandex.ru/d/S-YQPYSFcC3RgQ>

Размер зоны доступности 1000 м.

## Задание 5

Построить карту плотности точек по населению и оформить ее для печати.

Исходный файл <https://drive.google.com/file/d/1smnWbvkk1qE4rv5p8QWo108MGqcylMJH/view?usp=sharing>
